version: 2

jobs:
  build:
    environment:
      SSH_PUB_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA6tNSgBkWjnwnYuZUQB0oRGrv/IYlzyvUQRhm8eabgbhWaeGNarohkWXJgWw8s9BeAQm5z9wyHZ0vkdAIEtIJZLT1LTKFr8o9P4fzZUDVuGdRTA253q65lREb3yG9WjEEkCfIczzHwr+Pce68DRl9ZfMSeSYtweHDrjy98FW7yyJL3fkx0exVa6B1gKc6NAi4tZFyqH0sgOS1axXjusoUeXw9ouF1XBprDL0V762APpO+7YpuMTODLLcWHDQhR9dhjnncCaB2HZ+ptOCMtqKRFkBkfUjjHLboEyCGjjCZonEbqb7DdlZbRc0HhdBJM/Cd//nHOzon7w8HjH+YI9OB circleci@71f021696457"
    docker:
      - image: circleci/node:13.2.0
      - image: eu.gcr.io/devops-247114/deployers-test-container:v101
        environment:
          SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA6tNSgBkWjnwnYuZUQB0oRGrv/IYlzyvUQRhm8eabgbhWaeGNarohkWXJgWw8s9BeAQm5z9wyHZ0vkdAIEtIJZLT1LTKFr8o9P4fzZUDVuGdRTA253q65lREb3yG9WjEEkCfIczzHwr+Pce68DRl9ZfMSeSYtweHDrjy98FW7yyJL3fkx0exVa6B1gKc6NAi4tZFyqH0sgOS1axXjusoUeXw9ouF1XBprDL0V762APpO+7YpuMTODLLcWHDQhR9dhjnncCaB2HZ+ptOCMtqKRFkBkfUjjHLboEyCGjjCZonEbqb7DdlZbRc0HhdBJM/Cd//nHOzon7w8HjH+YI9OB circleci@71f021696457"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Prepare
          command: npm install --no-save
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Prepare e2e SSH tests
          command: |
            # Authorized key
            cat test/setup/id_rsa > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

            echo ${SSH_PUB_KEY} > ~/.ssh/id_rsa.pub
            chmod 644 ~/.ssh/id_rsa.pub

            #ssh-add

            # Config
            cp test/setup/ssh.config ~/.ssh/config
      - run:
          name: Test
          command: |
            npm test
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Typecheck
          command: |
            npm run typecheck
      - run:
          name: Build
          command: |
            npm run build
      - restore_cache:
          key: dependency-cache-e2e-{{ checksum "package.json" }}
      - run:
          name: E2e lib test
          working_directory: e2e
          command: |
            ./install-locally.sh
            npm i
            npm test
            git reset --hard
      - save_cache:
          key: dependency-cache-e2e-{{ checksum "package.json" }}
          paths:
            - ./e2e/node_modules
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run:
          name: Publish
          command: |
            git config user.email "ps-aux@ci.com"
            git config user.name "ps-aux-ci"
            export BUILD_NO=${CIRCLE_BUILD_NUM}
            version=$(scripts/get-version.js)
            npm version ${version} --allow-same-version
            npm run pub --no-git-tag-version
workflows:
  version: 2
  all:
    jobs:
      - build:
          context: NPM
