version: 2

jobs:
  build:
    environment:
      SSH_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----
                        MIIEogIBAAKCAQEAiAG5tw4PJah9Wujgrcu1TuCILe9lb2w+HPFI6Ip8Q5MJGelw
                        YS95sKzHMldk0/XhJZGKS4iFae60gAM9c2tIXIV4SWAHB8Y4rZqXeQZXW849gKWF
                        Okn1xIGakZZbJuO63KRoAUBnIhvtP+ElVLi1I7n3WVz6xdpGdHUD+h5MMF6j2L1t
                        MbLz5WsmSfLLwwqE8gQSiZSQHm2MDoiY0pk8Z7n8fFEIyucEZOZ7LLduxq6MHNJt
                        qf+rtME1WEiLcxfXH3SSfKb9esImuYoPYKOa+rqxImOBaT8zvZjUyjzWmm6a7r4m
                        g6LMqhLsyqRjC8ZdEY2+eG5tbNjCbL/3YJTCvQIDAQABAoIBAHRlxaM8jQoVoPLk
                        yyTyakEPOHzXnWA2qxHqDhO2MZNDi0550ovaLbNeqzwSP2CH1iBo5oquVD/M4v2L
                        yFO3RT6pm8BwRpQIuQkafPg+zRTs9QXcoqC4G3YJ1Vcz7t7hl1KuAbTQgXNXozxA
                        W8qeKahhx6bbRGN/4zxXyQeOVnYtyW9/9aW3E7ifv30fpVih/Sh0C6WPEYilXzBf
                        JtoMONvsAnO1qV54b3wLJNeoehe/bYG2koj6AX927Yhv+wyuwNyPojPwPXJOc5Ql
                        p8YVAqGTfbUK4f0qCbEcSFsfTxGuwLp7ntdtcwcWPEUCMuZ7cc2MzmTq0Q/hVUAi
                        p+FQUQECgYEAvVyLjNBEYn5KOy/J4hHlUT134bkeqIeUNmDfMhFAj38nGB72CCIT
                        6Gy36yaSwxvijgR2ZMO4joX3JSIlhJ5gLKCYbQkxyB/51+BdCCxGb4399ijZhjKc
                        /OqZsOPlSYuMzDS/YHQwobDHDqsPX5qwreN7Ot0/jjtSN/OAz2s1KtkCgYEAt957
                        +fzQa0iWRiVfotp7dU9TPx7YBaRBLm+hxgPTDqfr9Q2JBgtw2/n1hgr5r4AILiR2
                        q65j/D2J/rAINZ7jM7NBXm7h54gUHu4XwlJt/9VbyfFuICD/u1sX/+ZOmFYhg3cn
                        lyA5DHbAu9u+9+/Lx0+r7Zk+CM6ic2PZku0xgIUCgYBHWDrrzvw078ggDJ1Po9Z2
                        iWZFkW3PqWVaJ51wS7e7WPjtyZyA6/X8OBoDawEYqcTuJRhGVseOS0MWporkMJej
                        uM41JqWu9P05LLtgfO380c7BlBqAyUkEsY8+al7VGtLtjWIdgSlhgi09hY3BQ5MV
                        sQOY5gswF4GeuwvpGkdp4QKBgB/Vuptu5Vsd5z7f664Tq/qEsIImQfrAFLUIiPby
                        5JEOC/GS1V2hj3nWzmbV8aMsRL5Qe+d/uzoKIaFiMxmtl+L0r2W9RwnCatFsIdr4
                        UKlR9KGDVrDjZcO3ovEgnA0OJKFReR5Wauo4iWg9RNRCxYKNzdPGi5IUzNWzvREO
                        VlrNAoGAUEC60+Ag9SlStQyKWeEa6F2pH/B6O6/aXMyNjNRzWACIdmC25sfa79FU
                        vWQQnBbWhkDUwvFjzO7wejUO8nhXxeJ+EZjuiGHvyEgytEwoIpVzHx8h8BjqIjq6
                        w2h/VneCiTtXWWLirc/SYzO1rR6RDiF+MieDbRo1Oe4LQPVcoBo=
                        -----END RSA PRIVATE KEY-----"
    docker:
      - image: circleci/node:13.2.0
      - image: eu.gcr.io/devops-247114/deployers-test-container:20191226134045470501
        environment:
          SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCIAbm3Dg8lqH1a6OCty7VO4Igt72VvbD4c8UjoinxDkwkZ6XBhL3mwrMcyV2TT9eElkYpLiIVp7rSAAz1za0hchXhJYAcHxjitmpd5Bldbzj2ApYU6SfXEgZqRllsm47rcpGgBQGciG+0/4SVUuLUjufdZXPrF2kZ0dQP6HkwwXqPYvW0xsvPlayZJ8svDCoTyBBKJlJAebYwOiJjSmTxnufx8UQjK5wRk5nsst27Growc0m2p/6u0wTVYSItzF9cfdJJ8pv16wia5ig9go5r6urEiY4FpPzO9mNTKPNaabpruviaDosyqEuzKpGMLxl0Rjb54bm1s2MJsv/dglMK9"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Prepare
          command: npm install --no-save
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Prepare e2e SSH tests
          command: |
            # Authorized key
            echo ${SSH_PRIVATE_KEY} > ~/.ssh/id_rsa
            # Config
            cp test/setup/ssh.config ~/.ssh/config
      - run:
          name: Test
          command: |
            npm test
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Typecheck
          command: |
            npm run typecheck
      - run:
          name: Build
          command: |
            npm run build
      - restore_cache:
          key: dependency-cache-e2e-{{ checksum "package.json" }}
      - run:
          name: E2e lib test
          working_directory: e2e
          command: |
            ./install-locally.sh
            npm i
            npm test
            git reset --hard
      - save_cache:
          key: dependency-cache-e2e-{{ checksum "package.json" }}
          paths:
            - ./e2e/node_modules
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run:
          name: Publish
          command: |
            git config user.email "ps-aux@ci.com"
            git config user.name "ps-aux-ci"
            export BUILD_NO=${CIRCLE_BUILD_NUM}
            version=$(scripts/get-version.js)
            npm version ${version} --allow-same-version
            npm run pub --no-git-tag-version
workflows:
  version: 2
  all:
    jobs:
      - build:
          context: NPM
