version: 2

jobs:
  build:
    environment:
      SSH_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----
                        MIIEoQIBAAKCAQEAqa3lT3ADXZy2bF4BCVvSshK2fTC/FGuA3UY/A+/cAhOvgCn1
                        Z9agKmK7lsvIRcP93EZ8Brk1PAEiSV3QMWF0qdAKLZeViEBcl54OBX/WwdD8QYN9
                        8NuCXO3P/6Vh82buRAPFMcRMcnT9HgELLehelvYsOqyAr060M/9F/JotxqdcX1JA
                        UWS9DtVpXiQ0Afp/0KeeChRFwAunev4CpDtYvFYSyl84N/uMSzbMyEdKEcMRjkQW
                        xl42UHuEPYW/A2TZj0p9MveEpkZ52PtTSNSshsrOrLL2UyCKa3iEZftMJVp2rG7/
                        diubSrUYSqEMCj0IbP/3mM/gN36IqK7RX51cIQIDAQABAoIBAGcTYG31WdYQUTFb
                        mb2ZrlDG1V0Ps8Qv2kSRW86Ec14/nyl4U8AUvY+CEvr0KGFZQmoB124uLIybE70F
                        5GdbEIfn/YbcwtXWY2kndtUYZ9mtntAdlPAwKO1S+jwOt4YpTSy8LZqh6N7O+sSz
                        VZs5wdxrB0tNZ48XfJjpxhZBgvVdz+5ACBP+G2oqSABKqvXleY4ECyOCf99rnVwL
                        7VgyHEL1kC6Wj9LNi7JE55wHutiLqst16LPHNIPqvTbWrf0mqHRTZSPMzkN/rWqH
                        hCY+oyCIvIj3tzMbHKS7nX1j1TdqGBRkF0jUXkivtDrE6NGFNCEj38Z6Zrn0WGNk
                        O9LMFBECgYEA4JSJHCqux537Ped0hyaYLwYNw9D34aEYkIU5DEGI3EGzCmzugdbR
                        0UzjCzyTciKWrbc5r04yePHsgXG67010RJAoAnGBMZ+q+vreKctimHH9AxeSprPo
                        3b97pDp6bpnIIr8G7rqTypi1Xe94MGgKeQGSDIhd3qfchfEvNgCfIecCgYEAwWsN
                        hKFO5iKZL1S3reHWUgDpyRiJqEtsnamZ/+bHCMeU/p2lz4AE7voAkAbo6bSkaGyG
                        opCu9z88QnHzKYDfmI15nMokstwhNmxlV+enrAUW3IWJqacSvayhEELzy5jL64/O
                        ndt9ObuN6Dnrv22IqcS7dfe2rFHbdL067+v+4LcCgYEA3GqsT0rNE/pIFi/OvL7y
                        amSkqeW1BGwaMe2vWgoQCy0oTjkvtZtjfurZg7PGeyTbgk/se9Rh0TaQC1PWRvxb
                        +tcJjaxdQpkVNRN3bMnDUR+/VYOTWa4GBW3kKgGDHH4uYXvfj/rrBtLuXu2jps7W
                        SIF0GHzWtKtH0uYuke/2P00CgYA0eIlDSMtxrUMnTvFBb7nHp03E6y41BLkjkGYh
                        wQaPwC0QYc4gm5c7CYFrkSRQelv7pC1mHqAInRQI5obT5I1EAmVSfpg0GXm9HOzl
                        Swf2p67LBkMRTizMXe+XzMH8oqf3cJzZwDiZl+LodAYbeWiQvbkpSJk66D4Dzm4V
                        tkz/wwJ/ExAOmEOdMuUssQkENvOos6wXA0wtLF7H83sFP39UnMvlvOPcJKr2mPVl
                        B2WhSp0JbSSnNQfV1p+fq9BvhY3XEGdKf6uqxXivKVGfCiZH9p+41zqroinB37Zc
                        Lmy56emmU5EZZT+LL+m6QpMFxZPMYRDcfx69OAuAuUn5TYw67w==
                        -----END RSA PRIVATE KEY-----
"
    docker:
      - image: circleci/node:13.2.0
      - image: eu.gcr.io/devops-247114/deployers-test-container:20191226134045470501
        environment:
          SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpreVPcANdnLZsXgEJW9KyErZ9ML8Ua4DdRj8D79wCE6+AKfVn1qAqYruWy8hFw/3cRnwGuTU8ASJJXdAxYXSp0Aotl5WIQFyXng4Ff9bB0PxBg33w24Jc7c//pWHzZu5EA8UxxExydP0eAQst6F6W9iw6rICvTrQz/0X8mi3Gp1xfUkBRZL0O1WleJDQB+n/Qp54KFEXAC6d6/gKkO1i8VhLKXzg3+4xLNszIR0oRwxGORBbGXjZQe4Q9hb8DZNmPSn0y94SmRnnY+1NI1KyGys6ssvZTIIpreIRl+0wlWnasbv92K5tKtRhKoQwKPQhs//eYz+A3foiortFfnVwh circleci@9e736009a4de"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Prepare
          command: npm install --no-save
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Prepare e2e SSH tests
          command: |
            # Authorized key
            echo ${SSH_PRIVATE_KEY} > ~/.ssh/id_rsa
            # Config
            cp test/setup/ssh.config ~/.ssh/config
      - run:
          name: Test
          command: |
            npm test
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Typecheck
          command: |
            npm run typecheck
      - run:
          name: Build
          command: |
            npm run build
      - restore_cache:
          key: dependency-cache-e2e-{{ checksum "package.json" }}
      - run:
          name: E2e lib test
          working_directory: e2e
          command: |
            ./install-locally.sh
            npm i
            npm test
            git reset --hard
      - save_cache:
          key: dependency-cache-e2e-{{ checksum "package.json" }}
          paths:
            - ./e2e/node_modules
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run:
          name: Publish
          command: |
            git config user.email "ps-aux@ci.com"
            git config user.name "ps-aux-ci"
            export BUILD_NO=${CIRCLE_BUILD_NUM}
            version=$(scripts/get-version.js)
            npm version ${version} --allow-same-version
            npm run pub --no-git-tag-version
workflows:
  version: 2
  all:
    jobs:
      - build:
          context: NPM
