version: 2

jobs:
  build:
    environment:
      SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCs1QUUpSJsM+VO7cxZYJs9WsiKL74CeIIAeu2XHx310ilSQ9ok7/620CTeljPCBym8u87V466zdOg95u3IdldOENS427eOt2C4nKKTNAQojXn90s0gPKTaxKrdZFvyL2xlMXqIKjl1ry0euEy6AiRoMa2AFLBGjUeoE8UrK88HD+QsYY2VxL12HTvBX2D4y4HqPqzZtHzx49AMF1Sn/nQ/92/JsKsw8xq1dYTwqJ7y2ZIJ0wkaOYI2BeTWOG9eClbyXwtk3WFxhxaC13GKfUxyQ3ACuciSJ4IaZLiOZGQQHpKW8z0MGsMmA06TxVbz+DRh1s9vo+tLwHfaGzVW6vsh"
    docker:
      - image: circleci/node:13.2.0
      - image: eu.gcr.io/devops-247114/deployers-test-container:2019122613335717c0b0
        environment:
          SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCs1QUUpSJsM+VO7cxZYJs9WsiKL74CeIIAeu2XHx310ilSQ9ok7/620CTeljPCBym8u87V466zdOg95u3IdldOENS427eOt2C4nKKTNAQojXn90s0gPKTaxKrdZFvyL2xlMXqIKjl1ry0euEy6AiRoMa2AFLBGjUeoE8UrK88HD+QsYY2VxL12HTvBX2D4y4HqPqzZtHzx49AMF1Sn/nQ/92/JsKsw8xq1dYTwqJ7y2ZIJ0wkaOYI2BeTWOG9eClbyXwtk3WFxhxaC13GKfUxyQ3ACuciSJ4IaZLiOZGQQHpKW8z0MGsMmA06TxVbz+DRh1s9vo+tLwHfaGzVW6vsh"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Prepare
          command: npm install --no-save
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Prepare e2e SSH tests
          command: |
            # Authorized key
            echo ${SSH_AUTHORIZED_KEY} > ~/.ssh/id_rsa.pub
            # Config
            cp test/setup/ssh.config ~/.ssh/config
      - run:
          name: Test
          command: |
            npm test
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Typecheck
          command: |
            npm run typecheck
      - run:
          name: Build
          command: |
            npm run build
      - restore_cache:
          key: dependency-cache-e2e-{{ checksum "package.json" }}
      - run:
          name: E2e lib test
          working_directory: e2e
          command: |
            ./install-locally.sh
            npm i
            npm test
            git reset --hard
      - save_cache:
          key: dependency-cache-e2e-{{ checksum "package.json" }}
          paths:
            - ./e2e/node_modules
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run:
          name: Publish
          command: |
            git config user.email "ps-aux@ci.com"
            git config user.name "ps-aux-ci"
            export BUILD_NO=${CIRCLE_BUILD_NUM}
            version=$(scripts/get-version.js)
            npm version ${version} --allow-same-version
            npm run pub --no-git-tag-version
workflows:
  version: 2
  all:
    jobs:
      - build:
          context: NPM
