version: 2

jobs:
  build:
    environment:
      SSH_PUB_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA6tNSgBkWjnwnYuZUQB0oRGrv/IYlzyvUQRhm8eabgbhWaeGNarohkWXJgWw8s9BeAQm5z9wyHZ0vkdAIEtIJZLT1LTKFr8o9P4fzZUDVuGdRTA253q65lREb3yG9WjEEkCfIczzHwr+Pce68DRl9ZfMSeSYtweHDrjy98FW7yyJL3fkx0exVa6B1gKc6NAi4tZFyqH0sgOS1axXjusoUeXw9ouF1XBprDL0V762APpO+7YpuMTODLLcWHDQhR9dhjnncCaB2HZ+ptOCMtqKRFkBkfUjjHLboEyCGjjCZonEbqb7DdlZbRc0HhdBJM/Cd//nHOzon7w8HjH+YI9OB circleci@71f021696457"
      SSH_PRIVATE_KEY: |
                        -----BEGIN RSA PRIVATE KEY-----
                        MIIEpQIBAAKCAQEAwOrTUoAZFo58J2LmVEAdKERq7/yGJc8r1EEYZvHmm4G4Vmnh
                        jWq6IZFlyYFsPLPQXgEJuc/cMh2dL5HQCBLSCWS09S0yha/KPT+H82VA1bhnUUwN
                        ud6uuZURG98hvVoxBJAnyHM8x8K/j3HuvA0ZfWXzEnkmLcHhw648vfBVu8siS935
                        MdHsVWugdYCnOjQIuLWRcqh9LIDktWsV47rKFHl8PaLhdVwaawy9Fe+tgD6Tvu2K
                        bjEzgyy3Fhw0IUfXYY553Amgdh2fqbTgjLaikRZAZH1I4xy26BMgho4wmaJxG6m+
                        w3ZWW0XNB4XQSTPwnf/5xzs6J+8PB4x/mCPTgQIDAQABAoIBAQCRMSsSsG4xV9OB
                        ISIQzqAjKjsBm6Cq3B00hjmDYRQafarq/o1PDcBAe1mMKuf3V62+0jErs5EZ9sfS
                        gX98VA3YG/9Fd1rK2t7u8d20BcSiFUNNIFxEQ6Bk9BgITgrqo/K4aHZImtJn1d6u
                        ayUuSv2gLxaeFKfzUDRGPeBhY3xi9NHFoAc4EvSgWvjkD+zu2XmhBB/jrUv0gKXO
                        AuFoE5rNNwAAncQlixxyAQ7JKA+PyFMFPmRO9c5yGwXni+2KFgAdjvIQX2pRp0DW
                        SxtzaQev2G73sa8sUwBv4P5YtdYLi4+W/PTArFqehL+3GvjcD6MYEPbIerOwZzwR
                        LuvWUpQBAoGBAP3VBtMcUgJ9BuYrAeKO/zgDAYqEmsE8AlxkizZd71u93sllUD6y
                        OF5/30t+RG7/grA7QZdtnZT/lNQl96vgID1owOy+WZxtNJVSSjHfIEWK0RdSKwRb
                        7VE7I1GNnUkjTWo0FeeRcC5Jq+LjV4ogizA0JMAtWz+z463Nq1fcBHlRAoGBAMKQ
                        nah15qeKC3NGEaUZHyN9jqc0EsKYIjfwAGh8fRYEobrsQ78VWxJcQM8w3jU5QWgq
                        vw/PofpxW5jvAxoWfm6Vl63hPtsmxtr6c188EMCWk7mbVqdxOtUVSxToBSb7li2x
                        bkkvEf5obPoWF1Abs7JmzeHBUACKc2i9QiTSaCsxAoGBAJaJRxHeoths87F/Yg/O
                        BJhgWAKhX/Int7K5wkIM9Y5wDXddSXjVU07gATqReN5nVEdV7TF0Rdd+t/IVTkw1
                        kIk63efJf/WgYmYINo5bKJV1nUl6Zp6gMh9RtkGAff5JHHlWyILcIy6gbHsTnvAB
                        GusMkZsTiyE9e1KxPePOTSzxAoGAI+I2IZa1FptAJ19566ApfQswHyhceWVDkluC
                        R8MF8uShy269w+U1abp3/X5+zQQlSwfvOwRJVH5JrXgPc2VIpi6Sze/n/tU1AbgF
                        RUA3ur1Ku4WpwrIAbsJBmbZ9FMZ72SuLMpYq1GgACVO/sveY+cM6H3PexGrEhEG7
                        jDz+F1ECgYEAtU8HKxn4g7yuKIhDYPu7fdeUHarqlKZbiEt77bB+lIzunwWFhlII
                        sp4EtzOIJ+7/mwI4mMDxW/j5OAkzgrPS7ufp9gIsol1L5rH11lpHkVsZvlMo3XRQ
                        8tWOn9Y7ET7+boZxh0o/D3B3c1VIUemf9FxYa6zAMQJ7Yf8SjpaV4KU=
                        -----END RSA PRIVATE KEY-----
    docker:
      - image: circleci/node:13.2.0
      - image: eu.gcr.io/devops-247114/deployers-test-container:v101
        environment:
          SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA6tNSgBkWjnwnYuZUQB0oRGrv/IYlzyvUQRhm8eabgbhWaeGNarohkWXJgWw8s9BeAQm5z9wyHZ0vkdAIEtIJZLT1LTKFr8o9P4fzZUDVuGdRTA253q65lREb3yG9WjEEkCfIczzHwr+Pce68DRl9ZfMSeSYtweHDrjy98FW7yyJL3fkx0exVa6B1gKc6NAi4tZFyqH0sgOS1axXjusoUeXw9ouF1XBprDL0V762APpO+7YpuMTODLLcWHDQhR9dhjnncCaB2HZ+ptOCMtqKRFkBkfUjjHLboEyCGjjCZonEbqb7DdlZbRc0HhdBJM/Cd//nHOzon7w8HjH+YI9OB circleci@71f021696457"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Prepare
          command: npm install --no-save
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Prepare e2e SSH tests
          command: |
            # Authorized key
            echo ${SSH_PRIVATE_KEY} > ~/.ssh/id_rsa
            echo ${SSH_PUB_KEY} > ~/.ssh/id_rsa.pub
            # Config
            cp test/setup/ssh.config ~/.ssh/config
      - run:
          name: Test
          command: |
            npm test
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Typecheck
          command: |
            npm run typecheck
      - run:
          name: Build
          command: |
            npm run build
      - restore_cache:
          key: dependency-cache-e2e-{{ checksum "package.json" }}
      - run:
          name: E2e lib test
          working_directory: e2e
          command: |
            ./install-locally.sh
            npm i
            npm test
            git reset --hard
      - save_cache:
          key: dependency-cache-e2e-{{ checksum "package.json" }}
          paths:
            - ./e2e/node_modules
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run:
          name: Publish
          command: |
            git config user.email "ps-aux@ci.com"
            git config user.name "ps-aux-ci"
            export BUILD_NO=${CIRCLE_BUILD_NUM}
            version=$(scripts/get-version.js)
            npm version ${version} --allow-same-version
            npm run pub --no-git-tag-version
workflows:
  version: 2
  all:
    jobs:
      - build:
          context: NPM
